### ISSUE TITLE
AES command - different key slots - ATECC608A

### ISSUE THREAD

**Issue by Grifenfer** [f-secure-foundry/armoryctl#2]
Hello, I modified the code in atecc608.go to use the AES command. I configurated the slots 0,1 and 2 with the SlotConfig and KeyConfig bytes so these slots could contain AES Key. The configurations are not secured, the goal was to have the most liberties on the slot (read and write easily).  

The SlotConfig bytes are :  0x00, 0x00 (byte 0, byte 1) for the three slots
The KeyConfig bytes are :  0x3a, 0x00 (byte 0, byte 1) for the three slots

The configuration and the data zone are locked after the configuration.

The AES command works fine for the slot 0 but doesn't work for the slots 1 and 2. The data to encrypt is the same for each key and is 0x00,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0xAA,0xBB,0xCC,0xDD,0xEE,0xFF

For the slot 1 (address = 0x08, 0x00 (byte 0, byte 1), address found on the full datasheet of the ATECC608A), I have an execution error at the encryption command.
For the slot 2 (address = 0x10, 0x00 (byte 0, byte 1), address found on the full datasheet of the ATECC608A), I have a parse error at the encryption command.

In attached files you will find the modifications I made for the atecc608.go file.

I don't see what I am doing wrong. Could you help me ?
[atecc608_moified.zip](https://github.com/f-secure-foundry/armoryctl/files/6992447/atecc608_moified.zip)

**Comment by abarisani** [comment]
This is not an issue specific to this library but rather a generic ATECC608A configuration inquiry, I am afraid we don't provide support for the generic use and configuration of the ATECC608A unless it exhibits a bug/defect in the library itself.

The [previous issue](https://github.com/f-secure-foundry/armoryctl/issues/1) highlights that there might be some issues with commands holding data (though I haven't identify any so far) which is why it remains valid.

Thank you for your understanding.
